server:
  port: 8080
student:
  id: 100
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://app_mysql:3306/docker?allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  redis:
    host: app_redis
  mail:
    host: smtp.163.com
    username: LintMar@163.com
    password: PSNUUUCTIAKHUWMP
mybatis:
  type-aliases-package: com.lintmar.springboot.bean
  mapper-locations: classpath:com.lintmar.springboot.mapper/*.xml
