server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bjpowernode?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  devtools:
    restart:
      enabled: false

mybatis:
  type-aliases-package: com.lintmar.springboot.bean
  mapper-locations: classpath:com.lintmar.springboot.mapper/*.xml
