server:
  port: 80

spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bjpowernode?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
mybatis:
  type-aliases-package: com.lintmar.lettuce.bean
  mapper-locations: classpath:com.lintmar.lettuce.mapper/*.xml
